#ifndef _SHADER_TYPE_H
#define _SHADER_TYPE_H

enum ShaderType
{
	SHADER_GREY_SOLID = 0,
	SHADER_GREY_SHADED,
	SHADER_COLOR_SOLID,
	SHADER_COLOR_SHADED,
	SHADER_TEXTURE_REPLACE,
	SHADER_TEXTURE_COLOR,
	SHADER_TEXTURE_TILE_REPLACE,

	TOTAL_SHADERS
};

#endif